### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by SirPeteThe1st** [kubaska/twitch-fox#4]
I do not know what kind of setting I have to fix to get visual and audio notifications on this addon, but I still am not getting any kind of alerts. I can't check my email as often which makes me miss out on my favorite streams. Please advise.

**Comment by kubaska** [comment]
Hi, sorry for responding so late. In addon options, under "Stream Notifications" you can set whether to display notifications or play sound alerts. Little under it you can also set notification volume.
I think somewhere this year Firefox broke playing ogg format that I used too so that might have affected you. I fixed it in newest version.
